language: ruby
cache:
  bundler: true
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database hotels_ascenda_test;' -U postgres
sudo: false
rvm:
  - 2.4.9
script:
  - bundle exec rails test
addons:
  postgresql: "9.6"