language: ruby
cache:
  bundler: true
  directories:
    - vendor/cache
before_install:
  - gem update --system
  - gem install bundler
sudo: false
rvm:
  - 2.5.0
  - 2.4.9
  - ruby-head
script:
  - bundle exec rails test

