language: ruby
cache:
  bundler: true
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database hotels_ascenda_test;' -U postgres
  - bundle exec rake db:create:all
  - bundle exec rake db:test:prepare
sudo: false
rvm:
  - 2.4.9
  - ruby-head
script:
  - bundle exec rails test
addons:
  postgresql: "9.6"