language: ruby
cache:
  bundler: true
  directories:
    - vendor/cache
sudo: false
rvm:
  - 2.5.0
  - 2.4.9
  - ruby-head
bundler_args: --jobs=3 --retry=3 --without development
script:
  - bundle exec rails test

